id: QmW3RpezLcXWSLJGQTBAkBPRFhYHNrjW2vUo3LtKtfFeeh
description: ""
tags: []
source: .
trigger:
    type: https
    method: POST
    paths:
        - /api/score
domains:
    - host_tower
execution:
    timeout: 20s
    memory: 10MB
    call: set
